### ISSUE TITLE
Merging .cpp into .h?

### ISSUE THREAD

**Issue by hrastnik** [Dovyski/cvui#10]
Have you considered putting all of the code in a single header file? It would perhaps be simpler for end users to include only the header file.

**Comment by Dovyski** [comment]
I completely agree with you. I decided to go with two files from the beginning because of portability, but I think that was overzealous. cvui depends on opencv exclusively, which is already multiplatform, so there are no portability issues.

I think merging the .cpp into the .h is a good move. I'm a big fan of header-only libs.

**Comment by Dovyski** [comment]
Fixed on 1144603ee16c682bf50f1757006c56582a35ca32. cvui is now a header-only lib :tada:
