### ISSUE TITLE
why both

### ISSUE THREAD

**Issue by coldstart01** [Dovyski/cvui#106]
Hi, love cvui.

Why does it seems that I need both cvui image and imshow to display an image. I've tried them individually but then they don't show anything at all.

`cvui::image(frame,` 25, 25, `im_with_keypoints);` 
...
`cvui::imshow(WINDOW1_NAME, frame);`

Thank you.

**Comment by WojOstr** [comment]
Hi, im not the specialist out there, but as far as I know you can put multiple images on frame, but it won't show up until you call imshow(window, frame), because you have to pass the frame to window to show it

**Comment by Dovyski** [comment]
The explanation provided by @WojOstr nailed it. For further understanding, @coldstart01 , the function `cvui::image()` is one (of the many) drawing primitives cvui has. They all work putting pixels in a `frame` (a  `cv::Mat`). When you are done drawing things (images, checkboxes, etc), you need to call OpenCV's function to show the frame in a window.

`cv::imshow()` is that function. Since cvui does a lot of heavy lifting under the hook, e.g. detect shortcut keys, it has its own version of imshow named `cvui::imshow`. In practice they do the same thing (show a frame in a window), but cvui's one some things extra.

Is it clear now?

**Comment by coldstart01** [comment]
Ive built a few GUIs with cvui and its lightweight construction has allowed me to control ooencv programs in real time with transparent overlays. Its easy, made my programs more responsive. For example i made an overlay that implemented in real time control over many if the params. Thanks for helping further understanding.

--

**Comment by Dovyski** [comment]
I am very glad to hear that, @coldstart01, thank you!
