### ISSUE TITLE
trackbar : improvement with "theStep" params

### ISSUE THREAD

**Issue by pthom** [Dovyski/cvui#17]
Hi Fernando,

Sorry to flood you with messages :-)

I have some remarks concerning the trackbar api, which could be improved a little I think.
 * the parameter “theStep” could be renamed to theDiscreteStep since 
it is only used whenever the option TRACKBAR_DISCRETE is active 
(and it is discarded otherwise)
* It would be interesting to make it the last parameter, since it is very rarely used (only if TRACKBAR_DISCRETE is on)
* (In that case, we could also avoid the need for the “TRACKBAR_DISCRETE” option, since theDiscreteStep default value would be 0, and the trackbar ought to be discrete only if this value is > 0
* there is a typo in the tracbar example (the label says that the step is 0.5, but it is 0.1)

![image](https://cloud.githubusercontent.com/assets/7694091/25554739/2a343ab8-2cd5-11e7-9e24-952e05988c47.png)

Cheers,
Pascal

**Comment by Dovyski** [comment]
Hi Pascal!

It's no flood at all, thanks for all your energy and contributions :)

> the parameter “theStep” could be renamed to theDiscreteStep since
it is only used whenever the option TRACKBAR_DISCRETE is active
(and it is discarded otherwise)
It would be interesting to make it the last parameter, since it is very rarely used (only if TRACKBAR_DISCRETE is on)

That's a great idea! I was not aware that `theStep` would only be used when the discrete behavior is in place.  Making the param the last one is also ok and well thought.

> (In that case, we could also avoid the need for the “TRACKBAR_DISCRETE” option, since theDiscreteStep default value would be 0, and the trackbar ought to be discrete only if this value is > 0

I like the idea of using default params to enable/disable the discrete behavior, but in this case, I think it will cause a bit of confusion. Assuming `TRACKBAR_DISCRETE` was removed, if a developer wants to enable the discrete behavior, it will have to provide the `theOptions` param with zero and then the `theDiscreteStep` to some value.

Requiring two values to enable the discrete behavior (`TRACKBAR_DISCRETE` and a value for `theDiscreteStep`) is not perfect either. What do you think?

> there is a typo in the tracbar example (the label says that the step is 0.5, but it is 0.1)

I will check that, thanks!

**Comment by pthom** [comment]
I agree: leaving the options TRACKBAR_DISCRETE will make the code clearer for the end user

**Comment by Dovyski** [comment]
Fixed in 670fc46f85c74d058717e6b63e960a9507eba7f2
