### ISSUE TITLE
Feature request: Support for multiple input windows

### ISSUE THREAD

**Issue by jmuncaster** [Dovyski/cvui#25]
Thank you for this library, I really like its simplicity and have found it to be very useful.

I have a use case where I have a system of modular image processing components I would like to have each component render its own UI in its own window. Looking at the source code, it would appear that this would not be supported in its current design - are there plans to support multiple windows in the future?

**Comment by Dovyski** [comment]
Thank you! I am glad you like and find it useful.

Regarding your question, yes, at the moment it is not possible to capture clicks and interactions of cvui components in more than one window. However it is possible to use cvui in more than one window at the time (since the rendering is not attached to any window).

My current project also needs the feature you suggested, so I definitely plan to support it in the near future. I already have some ideas for how to implement this with minimal additions to the existing API.

**Comment by Dovyski** [comment]
@jmuncaster I've just added support for multiple windows in cvui.

The API is not final and I still need to document this new feature, but the overall idea is to call cvui components of a particular window between `cvui::context(WINDOW_NAME)`  and `cvui::update(WINDOW_NAME)`: 

```cpp
#define WINDOW1 "window1"
#define WINDOW2 "window2"

main() {
  // new cvui::init() function allows automatic creation of windows
  const cv::String windows[] = { WINDOW1, WINDOW2 };
  cvui::init(windows, 2);

  cvui::context(WINDOW1);
  // render components of WINDOW1 here
  cvui::update(WINDOW1);

  cvui::context(WINDOW2);
  // render components of WINDOW2 here
  cvui::update(WINDOW2);
}
```

That way cvui knows that which components belong to which window. I added two new examples ([here](https://github.com/Dovyski/cvui/blob/dev/example/src/multiple-windows-complex/main.cpp) and [here](https://github.com/Dovyski/cvui/blob/dev/example/src/multiple-windows/main.cpp)) showing how to use cvui with multiple windows.

I would appreciate any feedback on the API and if it works for your needs.

**Comment by jmuncaster** [comment]
Looks good, I'll try it out!

**Comment by 4xle** [comment]
@Dovyski FYI: Tried running both linked examples and getting two errors from the latest dev-branch:
`'gMouse': is not a member of 'cvui::internal' cvui.h 1894`
`'gMouse': undeclared identifier cvui.h 1894`.

On a hunch, I checked a diff and `static cv::Point gMouse;` appears to have been removed from the internal namespace which was breaking the examples(for me, at least). Not sure if you have other plans, but I added it back in and examples run just fine for me.

**Comment by Dovyski** [comment]
Thank you for the heads up, @4xle ! The dev build broke because I recently merged a pull request that uses a mouse structured that is being transitioned to a new format (more robust). I will check on it soon.

**Comment by Dovyski** [comment]
I've finished the support for multiple windows in cvui. Thanks for all the help! I added three examples covering different use cases of multiple windows, i.e. [multiple-windows](https://github.com/Dovyski/cvui/tree/dev/example/src/multiple-windows), [multiple-windows-complex](https://github.com/Dovyski/cvui/tree/dev/example/src/multiple-windows-complex), and [multiple-windows-complex-mouse](https://github.com/Dovyski/cvui/tree/dev/example/src/multiple-windows-complex-mouse).

Since the work is finished, I'm closing this issue. Please feel free to continue posting here if you have anything to add. If you have found a bug, please open a new issue so I can keep track of things more easily.

**Comment by jmuncaster** [comment]
Working well for us, thanks!

**Comment by k-toffel** [comment]
Hey,
I have a bit of a problem with multiple windows. I have a bunch of buttons. When a button is pressed I need to do some checks, if the check is unsuccessfull an error window should pop up.
Everything works fine for buttons that aren't grouped, but as soon as they're in a beginRow() / endRow() section I get the error:

> [CVUI] Fatal error (code 2): Calling update() before finishing all begin*()/end*() calls. Did you forget to call a begin*() or an end*()? Check if every begin*() has an appropriate end*() call before you call update().

I had a quick look and found out that the error occures during the update() call for the error window. I guess a possible solution would be to add a "gStack" and it's "gStackCount" to the context type.

**Comment by Dovyski** [comment]
Thank you for the report and all the additional information, @k-toffel! I've have opened a [new issue](https://github.com/Dovyski/cvui/issues/28) to keep track of this bug. Your suggestion on how to fix the problem seems spot on. I will work on it.
