### ISSUE TITLE
error ? not handle when I press button default close [x] ? 

### ISSUE THREAD

**Issue by baoson202** [Dovyski/cvui#29]
i see when i press button default close [x] ?  i can't handle button, text ... 
Please help ! Thank you !

**Comment by Dovyski** [comment]
The behavior you described usually happens when you close the window, but your code still calls `cv::imshow()` or `cvui::imshow()` after that. `imshow()` will "revive" any closed window, however cvui will not be able to track it anymore (because the callbacks were destroyed when the window was closed).

You can take a look at [this example](https://github.com/Dovyski/cvui/blob/dev/example/src/multiple-windows-complex-dynamic/main.cpp) which checks if a window is still open before using `imshow()`. Additionally you can call `cvui::watch()` on the window again to make sure cvui is able to track it properly.
