### ISSUE TITLE
Add OpenCV 2 Version

### ISSUE THREAD

**Issue by mjcorriere** [Dovyski/cvui#3]
Your library is fantastic. However, I am an OpenCV 2.X user and I had to make modifications to your library for it to work. 

All of these modifications were simple -- i.e. changing cv::LINE_AA to CV_AA, changing cv::FILLED to CV_FILLED, and so on. There is nothing in the library that has a hard OpenCV 3 dependency.

For that reason, would you consider adding OpenCV 2.X support out of the box for future development?

**Comment by Dovyski** [comment]
Thank you! Sure I would love to have support for OpenCV 2.x out of the box. 

I appreciate your guidance about the changes I should make. I will incorporate them in the next release.

**Comment by mjcorriere** [comment]
Great!

I'd be happy to do the porting of your current version and submit a merge request on a separate branch. Let me know if you want me to and how you'd like it done.

**Comment by Dovyski** [comment]
I definitely want you to do a pull request  :smile:. I've added a few new things to the lib since it was released, so I would appreciate if you could use the [dev](https://github.com/Dovyski/cvui/tree/dev) branch as your starting point.

About the implementation, I think the easiest way of supporting 2.x out of the box is to replace constants in the format `cv::THING`  with their  `CV_THING` equivalent, as you already suggested. I'm ok with that.

**Comment by Dovyski** [comment]
Support for opencv 2 has been added in 6900b752809f67f55536142fe05a12d252b6a97e. I hope you haven't started working on this, @mjcorriere.

I''m closing this issue as fixed.
